name: socuellamo
description: Flutter project that will contain the information of important events and locations in the Socuellamo town.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: null

flutter:
  uses-material-design: true
